# Generated by Django 4.0.5 on 2022-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_excerpt_book_genre_book_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='excerpt',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
