# Generated by Django 4.0.5 on 2022-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_book_excerpt_alter_book_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='large_image',
            field=models.ImageField(blank=True, help_text='300px width, 450px height', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_image',
            field=models.ImageField(blank=True, help_text='200px width, 300px height', null=True, upload_to=''),
        ),
    ]
