# Generated by Django 4.0.5 on 2022-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_book_large_image_alter_book_small_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
