# Generated by Django 4.0.5 on 2022-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_blurb_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='quote',
            field=models.TextField(blank=True, help_text='Text without qoute marks', null=True),
        ),
        migrations.AlterField(
            model_name='blurb',
            name='qoute',
            field=models.TextField(help_text='Text without qoute marks'),
        ),
    ]
