# Generated by Django 4.0.5 on 2022-07-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_blurb_quote_alter_blurb_qoute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blurb',
            name='qoute',
        ),
    ]
