# Generated by Django 4.0.5 on 2022-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_blurb_qoute'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
