# Generated by Django 4.0.5 on 2022-07-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_book_cover_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='excerpt',
            field=models.FileField(blank=True, null=True, upload_to='static/documents'),
        ),
    ]
